/* AFTERHOURS asset pipeline (three r128, no modules).
   Loaded as the FIRST script in index.html, before three.js, so the Blender GLBs start downloading while the 1+ MB of
   three / add-ons / afterhours.js is still being fetched and parsed. afterhours.js's bootstrap then hands the bytes to
   GLTFLoader (A.load). The GLBs are geometry-only, meshopt-compressed and quantized (tools/optimize_models.sh), so:
     - GLTFLoader needs setMeshoptDecoder (three@0.128.0/examples/js/libs/meshopt_decoder.js, 21 KB, from jsDelivr)
     - quantized int16 attributes are widened back to float32 here, because r128's BufferAttribute.getX() does not
       de-normalize and the game bakes / merges these geometries on the CPU (glbParts, kitParts, mergeGeos).
   js/model-manifest.js (generated by the optimizer) gives each file's byte size, for a real progress bar, and a content
   hash used as ?v= so a re-exported GLB is never served stale from cache. */
(function(){
'use strict';
const ORDER=[ // [key, file]: first car on the select screen first, then the other cars, then the track kits
  ['kage','kage_r.glb'],['wisp','wisp_07.glb'],['autobahn','autobahn_63.glb'],['granfour','gran_four.glb'],['volcano','volcano_p1.glb'],['overload','overload_3k.glb'],
  ['blvd','blvd_kit.glb'],['philly','philly_kit.glb'],['mtairy','mtairy_kit.glb'],['calder','calder_kit.glb'],['caldertun','calder_tunnel_kit.glb'],['caldersets','calder_sets_kit.glb']];
const MAN=window.AH_MANIFEST||{};
const url=f=>'models/'+f+(MAN[f]?'?v='+MAN[f].v:'');
const A=window.AH_ASSETS={ order:ORDER, bytes:0, total:ORDER.reduce((s,o)=>s+((MAN[o[1]]||{}).bytes||0),0)||ORDER.length*1.2e6,
  lastByteAt:performance.now(), t0:performance.now(), bootShare:.6, listeners:[], fetched:{}, parsed:{} };
const got={}; // file -> bytes received so far
A.progress=()=>Math.min(1,ORDER.reduce((s,o)=>s+(got[o[1]]||0),0)/A.total); // main models only; the lod/ twins download later, off the progress bar
const tick=f=>{ if(f.startsWith('lod/')) return; A.lastByteAt=performance.now(); const bar=document.getElementById('bootbar'); // real download progress until the game takes the bar over
  if(bar&&!A.gameBooted) bar.style.width=(A.progress()*A.bootShare*100).toFixed(1)+'%'; };

/* streaming fetch with byte progress; resolves null (never rejects) so one bad file cannot block the others */
function grab(file,tries){
  return fetch(url(file),{cache:'default',priority:file.startsWith('lod/')?'low':'auto'}).then(res=>{
    if(!res.ok) throw new Error(res.status+' '+res.statusText);
    if(!res.body||!res.body.getReader) return res.arrayBuffer().then(b=>{ got[file]=b.byteLength; tick(file); return b; });
    const rd=res.body.getReader(), chunks=[]; let n=0;
    const pump=()=>rd.read().then(r=>{ if(r.done){ const out=new Uint8Array(n); let o=0; chunks.forEach(c=>{ out.set(c,o); o+=c.length; }); return out.buffer; }
      chunks.push(r.value); n+=r.value.length; got[file]=n; tick(file); return pump(); });
    return pump(); })
  .catch(e=>{ if(tries>0){ console.warn(file+' failed, retrying once (procedural fallback meanwhile)',e); got[file]=0;
      return new Promise(r=>setTimeout(r,3000)).then(()=>grab(file,tries-1)); }
    console.warn(file+' failed again',e); return null; });
}
if(location.protocol!=='file:'&&window.fetch) ORDER.forEach(([k,f])=>{ A.fetched[k]=grab(f,1); }); // start NOW, in priority order

/* widen quantized (int8/int16, normalized or not) attributes back to float32, then refresh bounds */
function widen(att){
  const il=att.isInterleavedBufferAttribute, arr=il?att.data.array:att.array;
  if(arr instanceof Float32Array&&!il) return att;
  const n=att.count, s=att.itemSize, out=new Float32Array(n*s), norm=!!att.normalized;
  const d=arr instanceof Int16Array?32767:arr instanceof Int8Array?127:arr instanceof Uint16Array?65535:arr instanceof Uint8Array?255:0;
  const get=['getX','getY','getZ','getW'];
  for(let i=0;i<n;i++) for(let k=0;k<s;k++){ const v=att[get[k]](i); out[i*s+k]=norm&&d?Math.max(v/d,-1):v; }
  return new THREE.BufferAttribute(out,s);
}
function widenScene(root){
  root.traverse(o=>{ if(!o.isMesh||!o.geometry) return; const g=o.geometry;
    for(const name of Object.keys(g.attributes)){ const a=g.attributes[name]; if(a.isInterleavedBufferAttribute||!(a.array instanceof Float32Array)) g.setAttribute(name,widen(a)); }
    g.computeBoundingBox(); g.computeBoundingSphere(); });
  return root;
}

let loader=null;
function getLoader(){ if(loader) return loader; loader=new THREE.GLTFLoader();
  if(window.MeshoptDecoder) loader.setMeshoptDecoder(window.MeshoptDecoder); else console.warn('MeshoptDecoder missing: compressed models will not load');
  return loader; }
/* parse one fetched GLB into a scene (meshopt decode + widen); resolves null on failure */
A.parse=function(key){
  return (A.fetched[key]||Promise.resolve(null)).then(buf=>{ if(!buf) return null;
    return new Promise(res=>getLoader().parse(buf,'',gl=>res(widenScene(gl.scene)),e=>{ console.warn(key+' parse failed',e); res(null); })); }); };
/* load everything: onScene(key, scene, isLod) fires per model as soon as it is parsed; the returned promise settles when the
   MAIN models have (that is what gates the game boot). Parsing runs one at a time, in priority order, so the first car is
   on screen before the heavy kits are decoded. Afterwards the lod/ twins (rival cars, ~30% of the triangles) are fetched at
   low priority and handed over the same way; the game uses them only once they have arrived. */
A.load=function(onScene){
  A.lastByteAt=performance.now(); // downloads may have finished long before the scripts did: restart the stall clock for decoding
  let chain=Promise.resolve();
  const main=Promise.all(ORDER.map(([k])=>{ chain=chain.then(()=>A.parse(k)).then(sc=>{ if(sc) onScene(k,sc,false); return sc; }); return chain; }));
  main.then(()=>{ if(location.protocol==='file:'||!window.fetch) return; let lc=Promise.resolve();
    ORDER.forEach(([k,f])=>{ const p='lod/'+f; if(!MAN[p]) return; const dl=grab(p,1); // all twins download together, parse one by one
      lc=lc.then(()=>dl).then(buf=>{ if(!buf) return; return new Promise(res=>getLoader().parse(buf,'',gl=>{ onScene(k,widenScene(gl.scene),true); res(); },e=>{ console.warn(p+' parse failed',e); res(); })); }); }); });
  return main; };
})();
