window.AH_CONCEPTS=[
  {id:'issue',name:'Issue 01 (evolved)',tag:'Current DNA',pitch:'Magazine spread: giant headline, stamp, handwritten note, footer panel.',
    notes:'<strong>Best if</strong> you want the original editorial identity with tighter settings.'},
  {id:'cockpit',name:'Night cockpit',tag:'Racing first',pitch:'Instrument panel: amber chips, compact title, spec card footer.',
    notes:'<strong>Best if</strong> race readability and dash-like HUD matter most.'},
  {id:'glass',name:'Glass dock',tag:'Mobile native',pitch:'Pill settings dock and frosted glass footer.',
    notes:'<strong>Best if</strong> you want thumbs-first, low noise on phones.'},
  {id:'neon',name:'Neon wire',tag:'Bold night',pitch:'Cyan/magenta neon edges and glowing CTAs.',
    notes:'<strong>Best if</strong> you want harbor-tunnel arcade energy.'},
  {id:'neon-glass',name:'Neon + Glass',tag:'Hybrid',pitch:'Glass dock + frosted footer with neon accents.',
    notes:'<strong>Best if</strong> you want mobile chrome and night energy together.'},
  {id:'broadsheet',name:'Broadsheet tear-off',tag:'Print maximal',pitch:'Cream tear-off footer, red stamp, tabloid masthead.',
    notes:'<strong>Best if</strong> story and print metaphor lead the brand.'},
  {id:'glass-cockpit',name:'Glass + Cockpit',tag:'Hybrid',pitch:'Frosted glass footer and dock, but amber stat bars and chip settings.',
    notes:'<strong>Try on</strong> trucks/SUVs — glass readability with warm motorsport data.'},
  {id:'editorial-glass',name:'Editorial + Glass',tag:'Hybrid',pitch:'Full magazine headline + stamp; only the footer becomes glass (no neon).',
    notes:'<strong>Best if</strong> you love Issue 01 type but want cleaner mobile footers.'},
  {id:'neon-broadsheet',name:'Neon Broadsheet',tag:'Hybrid',pitch:'Cream ink footer and caprow; neon masthead, stamp, and CTA outline.',
    notes:'<strong>Best if</strong> print storytelling meets night-street color.'},
  {id:'wire-cockpit',name:'Wire + Cockpit',tag:'Hybrid',pitch:'Cockpit layout with cyan/magenta neon on gauges and chips instead of amber.',
    notes:'<strong>Best if</strong> you want arcade night without glass blur.'},
  {id:'issue-neon',name:'Issue + Neon',tag:'Hybrid',pitch:'Keep magazine layout; add neon only on stamp, hand note, and stat bars.',
    notes:'<strong>Low risk</strong> editorial upgrade — 3D stays neutral.'},
  {id:'soft-glass',name:'Soft glass',tag:'Calm',pitch:'Glass dock/footer with muted ice palette (no magenta/cyan glow).',
    notes:'<strong>Best if</strong> glass layout without arcade or green cast.'},
  {id:'cockpit-broadsheet',name:'Cockpit + Broadsheet',tag:'Hybrid',pitch:'Amber dash chips and gauge; cream tear-off footer and tabloid masthead.',
    notes:'<strong>Best if</strong> race HUD clarity meets print storytelling in the footer.'},
  {id:'issue-glass',name:'Issue + Glass',tag:'Hybrid',pitch:'Full Issue 01 headline, stamp, and hand note; pill dock and frosted footer only.',
    notes:'<strong>Best if</strong> editorial hero stays intact but chrome goes native-mobile.'},
  {id:'broadsheet-glass',name:'Broadsheet + Glass',tag:'Hybrid',pitch:'Tabloid masthead and red stamp; stats sit in a glass card over cream ink.',
    notes:'<strong>Best if</strong> print color block needs modern thumb reach.'},
  {id:'soft-cockpit',name:'Soft + Cockpit',tag:'Hybrid',pitch:'Muted ice glass dock; amber stat bars and center gauge like cockpit.',
    notes:'<strong>Best if</strong> you want warm motorsport data without neon arcade.'},
  {id:'neon-soft',name:'Neon soft',tag:'Hybrid',pitch:'Soft glass layout with whisper neon: cyan dock ring, pink stamp glow only.',
    notes:'<strong>Best if</strong> night energy at 30% — avoids grade wash on 3D.'},
  {id:'editorial-cockpit',name:'Editorial + Cockpit',tag:'Hybrid',pitch:'Magazine headline and stamp stay; tools hide, chips + compact spec card footer.',
    notes:'<strong>Best if</strong> brand story up top, instrument panel below.'},
  {id:'wire-broadsheet',name:'Wire + Broadsheet',tag:'Hybrid',pitch:'Neon wire scene and outline CTA; cream footer and caprow like tear-off.',
    notes:'<strong>Best if</strong> tunnel arcade meets newsprint payoff.'},
  {id:'glass-tabloid',name:'Glass tabloid',tag:'Hybrid',pitch:'Oversized masthead and cream footer; frosted pill dock bridges both worlds.',
    notes:'<strong>Best if</strong> bold print type with iOS-style settings rail.'},
  {id:'tabloid-cockpit',name:'Tabloid + Cockpit',tag:'Hybrid',pitch:'Broadsheet masthead and red stamp; amber gauge, chips, and spec card footer.',
    notes:'<strong>Best if</strong> loud print header with serious race instrumentation below.'},
  {id:'issue-broadsheet',name:'Issue + Broadsheet',tag:'Hybrid',pitch:'Issue 01 headline, stamp, and swipe note; cream tear-off footer and ink stats.',
    notes:'<strong>Best if</strong> editorial car hero with tabloid payoff in the panel.'},
  {id:'ice-neon-wire',name:'Ice neon wire',tag:'Hybrid',pitch:'Cooler scanline scene; neon trimmed to 50% opacity on masthead, bars, and outline CTA.',
    notes:'<strong>Best if</strong> wire energy without blowing out the 3D car.'},
  {id:'neon-issue-glass',name:'Neon · Issue · Glass',tag:'Triple',pitch:'Glass dock + frosted footer; magazine type; neon on masthead, stamp, and gradient CTA only.',
    notes:'<strong>Ship candidate</strong> cousin to production hybrid — editorial + mobile + accent color.'},
  {id:'soft-broadsheet',name:'Soft + Broadsheet',tag:'Hybrid',pitch:'Muted ice glass dock; cream tear-off footer, ink stats, and red stamp.',
    notes:'<strong>Best if</strong> print payoff without neon or amber dash noise.'},
  {id:'cockpit-ice',name:'Cockpit ice',tag:'Hybrid',pitch:'Cockpit chips and gauge; ice-blue stat bars and cool spec card (no magenta).',
    notes:'<strong>Best if</strong> instrument layout with arctic night palette.'},
  {id:'glass-harbor',name:'Glass harbor',tag:'Hybrid',pitch:'Standard glass chrome; harbor cyan only on masthead, dock ring, and CTA gradient.',
    notes:'<strong>Best if</strong> you want glass UX with a single neon accent color.'},
  {id:'cream-neon-glass',name:'Cream neon glass',tag:'Triple',pitch:'Frosted glass frame around a cream stats block; neon gradient on bars and outline race button.',
    notes:'<strong>Best if</strong> broadsheet readability inside neon-glass mobile shell.'},
  {id:'wire-soft-glass',name:'Wire + soft glass',tag:'Hybrid',pitch:'Ice scanline scene; soft glass dock/footer without hot magenta on the car.',
    notes:'<strong>Best if</strong> arcade atmosphere with calm mobile chrome.'},
  {id:'issue-wire-cockpit',name:'Issue + wire cockpit',tag:'Triple',pitch:'Magazine headline and stamp; neon wire chips and gradient bars in cockpit card.',
    notes:'<strong>Best if</strong> story-first top, synth dash bottom.'},
  {id:'broadsheet-harbor',name:'Broadsheet harbor',tag:'Hybrid',pitch:'Cream tear-off and tabloid masthead; single cyan harbor accent (no pink).',
    notes:'<strong>Best if</strong> print footer with one night-street color.'},
  {id:'tabloid-neon-glass',name:'Tabloid neon glass',tag:'Triple',pitch:'Glass tabloid layout; full cyan/magenta neon on masthead, dock, and glass footer edge.',
    notes:'<strong>Best if</strong> maximal type + production-like hybrid chrome.'},
  {id:'soft-editorial-neon',name:'Soft editorial neon',tag:'Hybrid',pitch:'Issue headline and glass footer; neon only on hand note and stat gradient (no masthead glow).',
    notes:'<strong>Best if</strong> subtle upgrade path from Issue 01.'},
  {id:'cockpit-glass-harbor',name:'Cockpit glass harbor',tag:'Triple',pitch:'Glass dock, amber gauge, harbor cyan on chips and CTA rim.',
    notes:'<strong>Best if</strong> warm dash data with cool accent thread.'},
  {id:'issue-tabloid-neon',name:'Issue tabloid neon',tag:'Triple',pitch:'Tabloid masthead over magazine headline; neon stamp; cream footer with gradient bars.',
    notes:'<strong>Best if</strong> you cannot choose print vs editorial.'},
  {id:'neon-broadsheet-glass',name:'Neon broadsheet glass',tag:'Triple',pitch:'Neon broadsheet colors inside frosted margins; cream panel inset like a mounted clipping.',
    notes:'<strong>Best if</strong> tear-off story framed by night-street UI.'},
  {id:'harbor-soft-cockpit',name:'Harbor soft cockpit',tag:'Triple',pitch:'Soft glass dock; harbor cyan chips; amber gauge and bars in frosted card.',
    notes:'<strong>Best if</strong> calm chrome with two-tone motorsport readouts.'},
  {id:'wire-issue-glass',name:'Wire + issue + glass',tag:'Triple',pitch:'Magazine hero on ice-wire scene; glass footer keeps 3D neutral under the fold.',
    notes:'<strong>Best if</strong> atmosphere above, readable panel below.'},
  {id:'broadsheet-ice',name:'Broadsheet ice',tag:'Hybrid',pitch:'Full cream tear-off; tabloid header; ice-blue stat bars instead of black ink.',
    notes:'<strong>Best if</strong> print metaphor with cold night palette.'},
  {id:'tabloid-wire-soft',name:'Tabloid wire soft',tag:'Triple',pitch:'Tabloid masthead on scanline scene; soft glass dock; pink/cyan trimmed to footer only.',
    notes:'<strong>Best if</strong> loud type, quiet chrome, controlled glow.'}
];
