window.AH_CONCEPTS=[
  {id:'issue',name:'Issue 01 (evolved)',tag:'Current DNA',pitch:'Magazine spread: giant headline, stamp, handwritten note, footer panel.',
    notes:'<strong>Best if</strong> you want the original editorial identity with tighter settings.'},
  {id:'cockpit',name:'Night cockpit',tag:'Racing first',pitch:'Instrument panel: amber chips, compact title, spec card footer.',
    notes:'<strong>Best if</strong> race readability and dash-like HUD matter most.'},
  {id:'glass',name:'Glass dock',tag:'Mobile native',pitch:'Pill settings dock and frosted glass footer.',
    notes:'<strong>Best if</strong> you want thumbs-first, low noise on phones.'},
  {id:'neon',name:'Neon wire',tag:'Bold night',pitch:'Cyan/magenta neon edges and glowing CTAs.',
    notes:'<strong>Best if</strong> you want harbor-tunnel arcade energy.'},
  {id:'neon-glass',name:'Neon + Glass',tag:'Hybrid',pitch:'Glass dock + frosted footer with neon accents.',
    notes:'<strong>Best if</strong> you want mobile chrome and night energy together.'},
  {id:'broadsheet',name:'Broadsheet tear-off',tag:'Print maximal',pitch:'Cream tear-off footer, red stamp, tabloid masthead.',
    notes:'<strong>Best if</strong> story and print metaphor lead the brand.'},
  {id:'glass-cockpit',name:'Glass + Cockpit',tag:'Hybrid',pitch:'Frosted glass footer and dock, but amber stat bars and chip settings.',
    notes:'<strong>Try on</strong> trucks/SUVs — glass readability with warm motorsport data.'},
  {id:'editorial-glass',name:'Editorial + Glass',tag:'Hybrid',pitch:'Full magazine headline + stamp; only the footer becomes glass (no neon).',
    notes:'<strong>Best if</strong> you love Issue 01 type but want cleaner mobile footers.'},
  {id:'neon-broadsheet',name:'Neon Broadsheet',tag:'Hybrid',pitch:'Cream ink footer and caprow; neon masthead, stamp, and CTA outline.',
    notes:'<strong>Best if</strong> print storytelling meets night-street color.'},
  {id:'wire-cockpit',name:'Wire + Cockpit',tag:'Hybrid',pitch:'Cockpit layout with cyan/magenta neon on gauges and chips instead of amber.',
    notes:'<strong>Best if</strong> you want arcade night without glass blur.'},
  {id:'issue-neon',name:'Issue + Neon',tag:'Hybrid',pitch:'Keep magazine layout; add neon only on stamp, hand note, and stat bars.',
    notes:'<strong>Low risk</strong> editorial upgrade — 3D stays neutral.'},
  {id:'soft-glass',name:'Soft glass',tag:'Calm',pitch:'Glass dock/footer with muted ice palette (no magenta/cyan glow).',
    notes:'<strong>Best if</strong> glass layout without arcade or green cast.'},
  {id:'cockpit-broadsheet',name:'Cockpit + Broadsheet',tag:'Hybrid',pitch:'Amber dash chips and gauge; cream tear-off footer and tabloid masthead.',
    notes:'<strong>Best if</strong> race HUD clarity meets print storytelling in the footer.'},
  {id:'issue-glass',name:'Issue + Glass',tag:'Hybrid',pitch:'Full Issue 01 headline, stamp, and hand note; pill dock and frosted footer only.',
    notes:'<strong>Best if</strong> editorial hero stays intact but chrome goes native-mobile.'},
  {id:'broadsheet-glass',name:'Broadsheet + Glass',tag:'Hybrid',pitch:'Tabloid masthead and red stamp; stats sit in a glass card over cream ink.',
    notes:'<strong>Best if</strong> print color block needs modern thumb reach.'},
  {id:'soft-cockpit',name:'Soft + Cockpit',tag:'Hybrid',pitch:'Muted ice glass dock; amber stat bars and center gauge like cockpit.',
    notes:'<strong>Best if</strong> you want warm motorsport data without neon arcade.'},
  {id:'neon-soft',name:'Neon soft',tag:'Hybrid',pitch:'Soft glass layout with whisper neon: cyan dock ring, pink stamp glow only.',
    notes:'<strong>Best if</strong> night energy at 30% — avoids grade wash on 3D.'},
  {id:'editorial-cockpit',name:'Editorial + Cockpit',tag:'Hybrid',pitch:'Magazine headline and stamp stay; tools hide, chips + compact spec card footer.',
    notes:'<strong>Best if</strong> brand story up top, instrument panel below.'},
  {id:'wire-broadsheet',name:'Wire + Broadsheet',tag:'Hybrid',pitch:'Neon wire scene and outline CTA; cream footer and caprow like tear-off.',
    notes:'<strong>Best if</strong> tunnel arcade meets newsprint payoff.'},
  {id:'glass-tabloid',name:'Glass tabloid',tag:'Hybrid',pitch:'Oversized masthead and cream footer; frosted pill dock bridges both worlds.',
    notes:'<strong>Best if</strong> bold print type with iOS-style settings rail.'}
];
