// Track report: drives the game headless (?dev) and asks AHDEV.trackReport(id) for every event, then writes
// docs/track-report.md (a table per event) and docs/track-plans/<id>.png (plan view: straights, corners, brake boards,
// clearance warnings). The checks are the ZER0-G course checker (tools/track_design.py, MIT,
// https://github.com/witnesstodark/zer0-g) applied to our street tracks.
// usage: node tools/track_report.mjs [eventId ...]
// env: PLAYWRIGHT (path to playwright's index.mjs), CHROME (chromium binary), THREE_VENDOR (local three@0.128.0 package
// dir; without it the CDN is used).
import http from 'node:http';
import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { join, extname, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PW = process.env.PLAYWRIGHT || '/opt/npm-tools/node_modules/playwright/index.mjs';
const CHROME = process.env.CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const VENDOR = process.env.THREE_VENDOR || '/home/claude/vendor/package';
const { chromium } = await import(PW);
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.glb': 'model/gltf-binary', '.png': 'image/png', '.webp': 'image/webp', '.svg': 'image/svg+xml' };
const srv = http.createServer((q, s) => {
  const p = join(ROOT, decodeURIComponent(q.url.split('?')[0]));
  const f = existsSync(p) && statSync(p).isDirectory() ? join(p, 'index.html') : p;
  if (!existsSync(f)) { s.writeHead(404); return s.end(); }
  s.writeHead(200, { 'content-type': MIME[extname(f)] || 'application/octet-stream' }); s.end(readFileSync(f));
});
await new Promise(r => srv.listen(0, r));
const browser = await chromium.launch({ executablePath: existsSync(CHROME) ? CHROME : undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 640, height: 360 } });
page.setDefaultTimeout(180000);
await page.addInitScript(() => { let s = 12345; Math.random = () => { s = (s * 16807) % 2147483647; return s / 2147483647; }; });
if (existsSync(VENDOR)) {
  await page.route(/cdnjs\.cloudflare\.com\/ajax\/libs\/three\.js\/r128\/(.*)/, (rt, rq) => rt.fulfill({ path: join(VENDOR, 'build', rq.url().split('/').pop()) }));
  await page.route(/cdn\.jsdelivr\.net\/npm\/three@0\.128\.0\/(.*)/, (rt, rq) => rt.fulfill({ path: join(VENDOR, rq.url().split('three@0.128.0/')[1]) }));
}
await page.route(/fonts\.(googleapis|gstatic)\.com/, rt => rt.fulfill({ status: 200, contentType: 'text/css', body: '' }));
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto(`http://localhost:${srv.address().port}/index.html?dev`, { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.waitForFunction(() => window.AHDEV && window.AHDEV.trackReport, null, { timeout: 180000 });

const ids = process.argv.slice(2).length ? process.argv.slice(2) : await page.evaluate(() => AHDEV.events());
mkdirSync(join(ROOT, 'docs/track-plans'), { recursive: true });
const reps = [];
for (const id of ids) {
  const t0 = Date.now();
  const r = await page.evaluate(id => { const r = AHDEV.trackReport(id, { png: true, size: 520, noPlan: true }); return r; }, id).catch(e => ({ id, err: e.message }));
  if (!r || r.err) { console.log(id, 'FAILED', r && r.err); continue; }
  writeFileSync(join(ROOT, `docs/track-plans/${id}.png`), Buffer.from(r.png.split(',')[1], 'base64')); delete r.png;
  reps.push(r); console.log(`${id}: ${r.L} m, min R ${r.minR} m, ${r.straights.length} straights, ${r.corners.length} corners, ${r.clearance.warn.length} clearance warnings (${Date.now() - t0} ms)`);
}
await browser.close(); srv.close();

const mph = v => `${v} mph`;
let md = `# Track report

Generated by \`node tools/track_report.mjs\` from \`AHDEV.trackReport(id)\` (open the game with \`?dev\` to call it live).
The checks follow the ZER0-G course checker (\`tools/track_design.py\`, MIT, witnesstodark/zer0-g): length, tightest radius,
straights, a pace curve and self-clearance, plus a plan image per event in \`docs/track-plans/\`.

How to read it:

- **Straight** (S1, S2, ...): |curvature| under 0.0025 /m (radius over 400 m) for at least 120 m. Start \`s\` is metres from the start line.
- **Corner** (T1, T2, ... as labelled on the plan): |curvature| over 0.006 /m (radius under ~170 m) for at least 6 m. \`R\` is the apex radius, \`vC\` the most a
  reference car holds through it (stepRacer's lateral model v²·k/2 ≤ grip, grip 30, top 85 m/s), \`brake\` the brake-board
  distance before the corner entry from the speed you can carry off the run-in (braking 40 m/s²). A brake of 0 means a lift
  or flat-out corner. These are not lap-time predictions; they rank corners against each other.
- **Clearance**: two parts of the centreline more than 60 m apart along the lap that come closer than two road widths plus
  4 m in plan. Pairs more than 5 m apart in height are listed as crossings (bridges, tunnels), not warnings.
- Plan colours: grey straight, white sweeper, amber corner, pink hairpin (R < 50 m), yellow squares are brake boards over 30 m,
  red lines clearance warnings, green dot the start.

## Summary

| Event | Length | Road | Tightest R (at) | Straights | Longest | Straight % | Corners | Clearance warnings | Climb |
|---|---|---|---|---|---|---|---|---|---|
`;
for (const r of reps) md += `| ${r.name} (\`${r.id}\`) | ${r.L} m | ${r.W} m | ${r.minR} m (${r.minRat} m) | ${r.straights.length} | ${r.longest} m | ${r.straightPct}% | ${r.corners.length} | ${r.clearance.warn.length} | ${r.climb} m |\n`;
for (const r of reps) {
  md += `\n## ${r.name} (\`${r.id}\`)\n\n![${r.id} plan](track-plans/${r.id}.png)\n\n`;
  md += `${r.L} m lap, ${r.laps} laps, road ${r.W} m wide. Tightest radius ${r.minR} m at ${r.minRat} m. ${r.straightPct}% of the lap is straight.\n\n`;
  md += `Pace curve (corner radii in order, m): ${r.pace.length ? r.pace.join(' · ') : 'none'}\n\n`;
  md += `| Piece | Starts at | Length | R (apex) | Dir | vC | Run-in | Brake board |\n|---|---|---|---|---|---|---|---|\n`;
  const rows = [...r.straights.map((x, i) => ({ ...x, tag: 'S' + (i + 1) })), ...r.corners.map((x, i) => ({ ...x, tag: 'T' + (i + 1) }))].sort((a, b) => a.s - b.s);
  rows.forEach(x => {
    md += x.tag[0] === 'S' ? `| ${x.tag} straight | ${x.s} m | ${x.len} m | | | | | |\n`
      : `| ${x.tag} | ${x.s} m | ${x.len} m | ${x.R} m | ${x.dir} | ${mph(x.vC)} | ${x.runIn} m | ${x.brake ? x.brake + ' m' : 'flat / lift'} |\n`;
  });
  const cl = r.clearance;
  md += `\nClearance (need ${cl.need} m): ${cl.warn.length ? cl.warn.map(w => `${w.a}-${w.a1} m vs ${w.b} m: ${w.d} m apart`).join('; ') : 'no warnings'}.`;
  if (cl.cross.length) md += ` Crossings: ${cl.cross.map(w => `${w.a} m over/under ${w.b} m (${w.dy} m height gap)`).join('; ')}.`;
  md += '\n';
}
writeFileSync(join(ROOT, 'docs/track-report.md'), md);
console.log(`wrote docs/track-report.md (${reps.length} events)${errs.length ? '\npage errors:\n' + errs.join('\n') : ''}`);
